version: 2
jobs:
  build:
    docker:
      - image: rust:slim-buster
    steps:
      - run:
          name: Update apt package lists
          command: apt update
      - run:
          name: Update apt packages
          command: apt upgrade -y
      - run:
          name: Install dependent packages
          command: apt install git make libglib2.0-dev libcairo2-dev -y
      - checkout
      - run:
          name: rustup version
          command: rustup --version
      - restore_cache:
          keys:
            - cargo-lock-{{ checksum "Cargo.lock" }}
      - run:
          name: Build
          command: cargo build --release
      - run:
          name: Run test
          command: make test
      - run:
          name: Add rustup component rustfmt
          command: rustup component add rustfmt
      - run:
          name: Check coding format
          command: make style-check
      - run:
          name: Add rustup component clippy
          command: rustup component add clippy
      - run:
          name: Check lint
          command: make lint
      - run:
          name: Install rust-nightly
          command: rustup install nightly
      - run:
          name: Run benchmark
          command: make bench
      - save_cache:
          key: cargo-lock-{{ checksum "Cargo.lock" }}
          paths:
            - "/usr/local/cargo/registry"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
