version: 2
jobs:
  build:
    docker:
      - image: rust:slim-buster
    steps:
      - run:
          name: Update apt package lists
          command: apt update
      - run:
          name: Create checksum for apt package lists
          command: find /var/lib/apt/lists/ -type f | xargs sha1sum > /tmp/apt-cache.sum
      - restore_cache:
          keys:
            - apt-cache-{{ checksum "/tmp/apt-cache.sum" }}
            - apt-cache-
      - run:
          name: Install dependences
          command: apt install --download-only git libglib2.0-dev libcairo2-dev -y
      - run:
          name: Create checksum for apt package lists
          command: find /var/lib/apt/lists/ -type f | xargs sha1sum > /tmp/apt-cache.sum
      - save_cache:
          key: apt-cache-{{ checksum "/tmp/apt-cache.sum" }}
          paths:
            - "/var/lib/apt"
      - run:
          name: Update apt packages
          command: apt upgrade -y
      - run:
          name: Install dependences
          command: apt install git libglib2.0-dev libcairo2-dev -y
      - checkout
      - run:
          name: rustup version
          command: rustup --version
      - restore_cache:
          keys:
            - cargo-lock-{{ checksum "Cargo.lock" }}
      - run:
          name: Check coding format
          command: rustup component add rustfmt && cargo fmt -- --check
      - run:
          name: Build
          command: cargo build --release
      - run:
          name: Run test
          command: cargo test --all
      - save_cache:
          key: cargo-lock-{{ checksum "Cargo.lock" }}
          paths:
            - "/usr/local/cargo/registry"
            - "target"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
