version: 2
jobs:
  build:
    docker:
      - image: rust:slim-buster
    steps:
      - run:
          name: Update apt package lists
          command: apt update
      - run:
          name: Update apt packages
          command: apt upgrade -y
      - run:
          name: Download dependent packages
          command: apt install --download-only git libglib2.0-dev libcairo2-dev -y
      - run:
          name: Install dependent packages
          command: apt install git libglib2.0-dev libcairo2-dev -y
      - checkout
      - run:
          name: rustup version
          command: rustup --version
      - restore_cache:
          keys:
            - cargo-lock-{{ checksum "Cargo.lock" }}
      - run:
          name: Build
          command: cargo build --release
      - run:
          name: Run test
          command: cargo test -j 1 --no-fail-fast --all
      - run:
          name: Check coding format
          command: rustup component add rustfmt && cargo fmt -- --check
      - run:
          name: Run Clippy Lint
          command: rustup component add clippy && cargo clippy
      - save_cache:
          key: cargo-lock-{{ checksum "Cargo.lock" }}
          paths:
            - "/usr/local/cargo/registry"
            - "target"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
