version: 2
jobs:
  build:
    docker:
      - image: rust:slim-buster
    steps:
      - restore_cache:
          keys:
            - apt-cache
      - run:
          name: Update apt packages
          command: apt update && apt upgrade -y
      - run:
          name: Install dependences
          command: apt install git libglib2.0-dev libcairo2-dev -y
      - save_cache:
          key: apt-cache
          paths:
            - "/var/lib/apt/"
      - checkout
      - run:
          name: rustup version
          command: rustup --version
      - restore_cache:
          keys:
            - cargo-lock-{{ checksum "Cargo.lock" }}
      - run:
          name: Check coding format
          command: rustup component add rustfmt && cargo fmt -- --check
      - run:
          name: Build
          command: cargo build --release
      - run:
          name: Run test
          command: cargo test --all
      - save_cache:
          key: cargo-lock-{{ checksum "Cargo.lock" }}
          paths:
            - "/usr/local/cargo/registry"
            - "target"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
